### ISSUE TITLE
I want to know how to make a realtime apps and git stash

### ISSUE THREAD

**Issue by clasense4** [MokoVersity/mokoid-camp2-booklog#2]
1. Yeah you know `facebook`, `twitter`, `wizpert` (using `firebase`) or else that do realtime, so what is the best infrastructure behind it? 
   It said I have to learn about web socket (in my opinion I will using `socket.io`), message queue / service (`rabbitmq` or else).
   I have try [tornado](http://http://www.tornadoweb.org/en/stable/) too it has websocket module, but I'm still confused.
   And I've been reading about `Message Queuing Service` as a `middleware` to achieve realtime web-app over the cloud.
   So, can you guys give me a glance of how to implement it practically
2. Could you show me how to stash only one or two files and convert it to a branch instead of ignore them?

thanks

**Comment by jollen** [comment]
Please let me reply you in difference comments.
- Many real-time web apps are using WebSocket to implement server pushing. For server pushing, client must create a connection to the server. This kind of connection is usually persistent. WebSocket is TCP/IO based socket to create that kind of connection. We usually use socket.io for this. Node.js is very easy to implement real-time Web service. The main reason is that Node.js has a good Async IO behavior. While other technologies, like PHP, are Sync IO.

**Comment by jollen** [comment]
- There is no best and general purpose infrastructure for millions requests web apps. However, reserved proxy and load balancer are most often used infrastructure. To handle millions requests in real-time, we usually deploy our Node.js application server in several servers. It will be 100+ servers or even 1000+. The only thing we need to do is to place a load balancer in front of all Node.js servers. The load balancer is typically a HTTP request forwarder.
