### ISSUE TITLE
Scout : SASS GUI Compiler

### ISSUE THREAD

**Issue by galpratama** [MokoVersity/mokoid-camp2-booklog#6]
You can use this instead of running sass on terminal / command prompt
http://mhs.github.io/scout-app/

Video Tutorial :
http://www.youtube.com/watch?v=Fju3aXW6zLM&feature=youtu.be

**Comment by Denbagusengarso** [comment]
mentahannya ada ngga mas? duduknya sebelah mana ya :)

20MB jhe :D

**Comment by galpratama** [comment]
ada, meja ke 3 barisan ke 3 yang pake baju putih ada gambar tulang rusuk

**Comment by aghust** [comment]
makasih mas infonya... harus install adobe air dl baru bisa pake... :+1:
