### ISSUE TITLE
[ASK] Install bootstrap via bower

### ISSUE THREAD

**Issue by dieka2501** [MokoVersity/mokoid-camp2-booklog#8]
i was install bootstraps via bower, and i get this directory structure, which file i have to included to html file?
![bower](https://f.cloud.github.com/assets/319068/1312410/2c3b9196-3236-11e3-9a70-279e7b2c9617.png)

**Comment by hanksudo** [comment]
@dieka2501 

```
dist/css/bootstrap.min.css
```
